# Generated by Django 2.0.6 on 2019-03-05 16:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCollectorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
                ('accountCreationDate', models.DateField(default=datetime.datetime(2019, 3, 5, 16, 28, 55, 267910, tzinfo=utc))),
                ('rank', models.CharField(default='grunt', max_length=10)),
                ('userIDkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=300)),
                ('releaseDate', models.DateField(default=datetime.datetime(2019, 3, 5, 16, 28, 55, 268362, tzinfo=utc))),
                ('esbrRating', models.CharField(max_length=20)),
                ('gameMakeIdKey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gameApp.GameCollectorModel')),
            ],
        ),
    ]
